# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='set_name',
            field=models.CharField(default='0', help_text='用户姓名', max_length=40),
        ),
    ]
