# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_userprofile_set_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='set_name',
            new_name='name',
        ),
    ]
